{% set name = "lychee" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lycheeverse/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 21c52aab5eefb0fda578f8192dffc5b776954e585f5692b87079cbb52ac1d89c

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

test:
  commands:
    - lychee --help

about:
  home: https://github.com/lycheeverse/lychee
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Fast, async, resource-friendly link checker
  dev_url: https://github.com/lycheeverse/lychee

extra:
  recipe-maintainers:
    - danielnachun
